name: Block PR if Secrets Detected

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger on PR creation, synchronization, or re-opening
    branches:
      - main  # Change this to your target branch name (e.g., 'main' or 'develop')

jobs:
  secret-scanning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the PR code
      uses: actions/checkout@v3

    - name: Check for secrets using GitHub Secret Scanning
      run: |
        # GitHub Secret Scanning should already detect common secrets like AWS, GCP, etc.
        # If secrets are detected, the PR will be blocked.
        echo "Running GitHub Secret Scanning..."
        
        # Check if secrets were detected using GitHub API
        curl -s https://api.github.com/repos/${{ github.repository }}/vulnerability-alerts \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          | jq '.[] | select(.state == "open")' > vulnerabilities.json

        if [[ -s vulnerabilities.json ]]; then
          echo "Secrets found in the PR! Please remove them before merging."
          exit 1  # Fail the job to block the PR merge
        else
          echo "No secrets detected in GitHub Secret Scanning."
        fi

    - name: Comment on PR if secrets detected
      if: failure()  # This step only runs if the previous steps fail (i.e., secrets are found)
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"body": "🚨 Secret detected in the PR! Please remove any sensitive data before merging."}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
