name: Secret Detection

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger on PR creation, synchronization, or re-opening
    branches:
      - main  # Change this to your target branch name (e.g., 'main' or 'develop')

jobs:
  secret-scanning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the PR code
      uses: actions/checkout@v3

    - name: Check for secrets using GitHub Secret Scanning
      run: |
        echo "Running GitHub Secret Scanning..."
        
        # Get GitHub vulnerability alerts (Secret Scanning issues) for the PR
        response=$(curl -s \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/vulnerability-alerts")
        
        # Check if the response contains any open vulnerabilities
        if [[ "$response" == "[]" ]]; then
          echo "No secrets detected."
        else
          echo "Secrets found! Blocking PR merge."
          echo "$response" | jq '.'  # Optionally print the raw response for debugging
          exit 1  # Fail the job to block the PR merge
        fi

    - name: Comment on PR if secrets detected
      if: failure()  # This step only runs if the previous steps fail (i.e., secrets are found)
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"body": "🚨 Secret detected in the PR! Please remove any sensitive data before merging."}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
