name: DependencyReview

on:
  pull_request:
    branches:
      - main
      - master
      - develop  # Trigger on pull requests targeting main, master, and develop branches

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Dependency Review'
        id: dependency_review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: low
          comment-summary-in-pr: always
          license-check: false
